apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxmox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: proxmox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxmox-exporter
    spec:
      containers:
      - name: proxmox-exporter
        image: prompve/prometheus-pve-exporter:3.4.3
        ports:
        - name: http
          containerPort: 9221
        volumeMounts:
        - name: proxmox-exporter-conf
          mountPath: /etc/prometheus/pve.yml
          subPath: pve.yaml
        resources: 
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        env:
        - name: --config.file
          value: /etc/prometheus/pve.yml
      restartPolicy: Always
      volumes:
      - name: proxmox-exporter-conf
        configMap:
          name: proxmox-exporter-conf
  revisionHistoryLimit: 1