kind: Service
apiVersion: v1
metadata: 
  name: vrising-ports
  annotations:
    metallb.universe.tf/address-pool: pool08-vrising-bgp
spec:
  selector:
    app.kubernetes.io/name: vrising-server
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: vrising01
      port: 9876
      protocol: UDP
    - name: vrising02
      port: 9877
      protocol: UDP