apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-http
  namespace: argocd
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`argocd.k8s.lenin.nu`) 
    kind: Rule
    middlewares:
    - name: httpsredirect
    - name: ipallowlist-privnets
    services:
    - name: argocd-server
      port: 80
      namespace: argocd
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-https
  namespace: argocd
spec:
  entryPoints:
    - websecure
  tls:
    secretName: secret-argocd-k8s-lenin-nu
  routes:
  - kind: Rule
    middlewares:
    - name: ipallowlist-privnets
    match: Host(`argocd.k8s.lenin.nu`)
    priority: 10
    services:
    - name: argocd-server
      port: 80
  - kind: Rule
    match: Host(`argocd.k8s.lenin.nu`) && Header(`Content-Type`, `application/grpc`)
    middlewares:
    - name: ipallowlist-privnets
    priority: 11
    services:
    - name: argocd-server
      port: 80
      scheme: h2c