apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: cert-argocd-k8s-lenin-nu
spec:
  dnsNames:
    - "argocd.k8s.lenin.nu"
  secretName: secret-argocd-k8s-lenin-nu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always