apiVersion: v1
kind: Service
metadata:
  name: argocd-server-3
  namespace: argocd
  annotations:
    metallb.universe.tf/address-pool: pool04
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer