apiVersion: v1
kind: Service
metadata:
  name: argocd-server-2
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  loadBalancerIP: 192.168.100.20
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080