apiVersion: v1
items:
- apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    name: argo-http
    namespace: argocd
  spec:
    entryPoints:
    - web
    routes:
    - kind: Rule
      match: Host(`argocd.k8s.lenin.nu`)
      middlewares:
      - name: httpsredirect
        namespace: traefik
      services:
      - name: argocd-server
        port: 80
    - kind: Rule
      match: Host(`argocd.k8s.lenin.nu`)
      middlewares:
      - name: httpsredirect
        namespace: traefik
      services:
      - name: argo-server
        port: 2746
- apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    name: argo-https
    namespace: argocd
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`argocd.k8s.lenin.nu`)
      services:
      - name: argocd-server
        port: 80
    - kind: Rule
      match: Host(`argocd.k8s.lenin.nu`)
      services:
      - name: argo-server
        port: 2746
kind: List

