apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: cert-yopass-k8s-lenin-nu
spec:
  dnsNames:
    - "yopass.k8s.lenin.nu"
  secretName: secret-yopass-k8s-lenin-nu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  revisionHistoryLimit: 1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: cert-verysecurepassword-databra007-se
spec:
  dnsNames:
    - "verysecurepassword.databra007.se"
  secretName: secret--verysecurepassword-databra007-se
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  revisionHistoryLimit: 1