apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: httpsredirect
  namespace: tools
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: yopass-ipwhitelist
spec:
  ipWhiteList:
    sourceRange:
      - 192.168.0.0/24