apiVersion: v3
name: traefik
project: default
source:
  repoURL: 'https://traefik.github.io/charts'
  targetRevision: 20.3.0
  helm:
    valueFiles:
      - values.yaml
  chart: traefik
destination:
  server: 'https://kubernetes.default.svc'
  namespace: traefik