service:
  annotations:
    metallb.universe.tf/address-pool: pool02-traefik-bgp
  spec:
    externalTrafficPolicy: Local
ports:
  websecure:
    port: 8443
    expose: 
      default: true
    exposedPort: 443
    protocol: TCP
    http3:
      enabled: false
tlsStore:
  default:
    defaultCertificate:
      secretName: prod-k8s-lenin-nu-cert
image:
  tag: v3.5.5