service:
  annotations:
    metallb.universe.tf/address-pool: pool02-traefik-bgp
  spec:
    externalTrafficPolicy: Local
ports:
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    http3:
      enabled: false
    tls:
      enabled: true
      options: ""
      certResolver: ""
      domains: 
       - main: "*.k8s.lenin.nu"
tlsStore:
  default:
    defaultCertificate:
      secretName: k8s-lenin-nu-cert