apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgbouncer-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgbouncer-exporter
    spec:
      containers:
      - name: pgbouncer-exporter
        image: prometheuscommunity/pgbouncer-exporter:v0.6.0
        args: 
        - "--pgBouncer.connectionString=postgres://$(PG_USER)@192.168.103.10:5000/pgbouncer?sslmode=disable"
        ports:
        - name: http
          containerPort: 9127
        envFrom:
        - secretRef:
            name: pgbouncer-secret
        resources: 
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
  revisionHistoryLimit: 1