kind: Service
apiVersion: v1
metadata: 
  name: pgbouncer-01-svc
spec:
  selector:
    app.kubernetes.io/name: pgbouncer-exporter-01
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetport: 9127
---
kind: Service
apiVersion: v1
metadata: 
  name: pgbouncer-02-svc
spec:
  selector:
    app.kubernetes.io/name: pgbouncer-exporter-02
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetport: 9127
---
kind: Service
apiVersion: v1
metadata: 
  name: pgbouncer-03-svc
spec:
  selector:
    app.kubernetes.io/name: pgbouncer-exporter-03
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetport: 9127      