apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.40.1
          args:
            - "--storage.tsdb.retention.time=180d"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      initContainers:
      - name: change-ownership-container
        image: busybox
        command: ["/bin/chmod","-R","777", "/prometheus/"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-data-pvc
  revisionHistoryLimit: 1