apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-shortterm
  namespace: tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-shortterm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-shortterm
    spec:
      containers:
        - name: prometheus-shortterm
          image: prom/prometheus:v2.40.5
          args:
            - "--storage.tsdb.retention.time=2h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-lifecycle"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus-shortterm.yaml
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      initContainers:
      - name: change-ownership-container
        image: busybox
        command: ["/bin/chmod","-R","777", "/prometheus/"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf-shortterm
        - name: prometheus-storage-volume
          emptyDir:
            sizeLimit: 500Mi
  revisionHistoryLimit: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.40.5
          args:
            - "--storage.tsdb.retention.time=180d"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-lifecycle"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yaml
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      initContainers:
      - name: change-ownership-container
        image: busybox
        command: ["/bin/chmod","-R","777", "/prometheus/"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-data-pvc
  revisionHistoryLimit: 1
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-configcheck
  namespace: tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-configcheck
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-configcheck
    spec:
      containers:
        - name: prometheus-configcheck
          image: alpine:3.17.0
          command: ["/bin/sh"]
          args: ["-c", "cp /tmp/check.sh.src /tmp/check.sh; chmod +x /tmp/check.sh; apk --no-cache add curl bash; while true; do /tmp/check.sh /tmp/prometheus.yaml prometheus-svc:9090/-/reload; sleep 60; done "]
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /tmp/prometheus.yaml
            - name: prometheus-conf-script
              mountPath: /tmp/check.sh.src
              subPath: check-promconf.sh
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-server-conf
        - name: prometheus-conf-script
          configMap:
            name: prometheus-conf-checker
  revisionHistoryLimit: 1