resources:
 - deployment.yaml
 - crb/crb.yaml
 - pvc/pvc.yaml
 - service/service.yaml
 - service/ingressroute.yaml
 - service/middlewares.yaml
 - service/certificate.yaml

configMapGenerator:
  - name: prometheus-server-conf-shortterm
    files:
    - configmap/prometheus-shortterm.yaml
  - name: prometheus-conf-checker
    files:
    - configmap/check-promconf.sh
  - name: prometheus-conf-checker-env
    envs:
    - configmap/check-promconf.env
generatorOptions:
  disableNameSuffixHash: true