apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisel2-pool01
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool01-argocd
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisel2-pool02
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool02-traefik
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisel2-pool03
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool03