apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisel2-pool01
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool01-argocd
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-01
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-02
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-03
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisel2-pool02
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool02-traefik
  nodeSelectors:
  - matchExpressions:
    - key: app.kubernetes.io/name
      operator: in
      values:
      - traefik
#  - matchLabels:
#      app.kubernetes.io/name: traefik
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisel2-pool03
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool03
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-01
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-02
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-03