apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisel2-pool01
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool01-argocd
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-01
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-02
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-03