apiVersion: metallb.io/v1alpha1
kind: AddressPool
metadata:
  name: public-pool
  namespace: metallb-system
spec:
  protocol: layer2
  addresses:
    - 192.168.100.30 - 192.168.100.40
  autoassign: false
