apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool01-argocd
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.20
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool02-traefik
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.21
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool03
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.24-192.168.100.30