apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcenter-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vcenter-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vcenter-exporter
    spec:
      containers:
      - name: vcenter-exporter
        image: pryorda/vmware_exporter:v0.18.4
        ports:
        - name: http
          containerPort: 9272
        envFrom:
        - configMapRef:
            name: vcenter-exporter-env
        resources: 
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
  revisionHistoryLimit: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snmp-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snmp-exporter
    spec:
      containers:
      - name: snmp-exporter
        image: prom/snmp-exporter:v0.20.0
        ports:
        - name: http
          containerPort: 9116
        resources: 
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
  revisionHistoryLimit: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.4.0
        ports:
        - name: http
          containerPort: 9100
        resources: 
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
  revisionHistoryLimit: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ping-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ping-exporter
    spec:
      containers:
      - name: ping-exporter
        image: czerwonk/ping_exporter:latest
        ports:
        - name: http
          containerPort: 9427
        volumeMounts:
        - name: ping-exporter-conf
          mountPath: /config/config.yml
          subPath: ping_exporter.yaml
        resources: 
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
      volumes:
      - name: ping-exporter-conf
        configMap:
          name: ping-exporter-conf
  revisionHistoryLimit: 1
