apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - exporters/pgbouncer-exporter/deployment.yaml
  - exporters/pgbouncer-exporter/service.yaml
  - exporters/postgres-exporter/deployment.yaml
  - exporters/postgres-exporter/service.yaml
  - exporters/vcenter-exporter/deployment.yaml
  - exporters/vcenter-exporter/service.yaml
  - exporters/snmp-exporter/deployment.yaml
  - exporters/snmp-exporter/service.yaml
  - exporters/node-exporter/deployment.yaml
  - exporters/node-exporter/service.yaml
  - exporters/ping-exporter/deployment.yaml
  - exporters/ping-exporter/service.yaml
  - exporters/script-exporter/deployment.yaml
  - exporters/script-exporter/service.yaml
  - exporters/pihole-exporter/deployment.yaml
  - exporters/pihole-exporter/service.yaml
  - exporters/proxmox-exporter/deployment.yaml
  - exporters/proxmox-exporter/service.yaml


configMapGenerator:
  - name: script-exporter-config
    files:
    - exporters/script-exporter/config.yaml
  - name: script-exporter-script1
    files:
    - exporters/script-exporter/script1.sh


generatorOptions:
  disableNameSuffixHash: true