apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
#  - ingress/middleware.yaml

  - deployment.yaml
  - service/service.yaml

configMapGenerator:
  - name: script_exporter_config
    files:
    - script_exporter/config.yml
  - name: script_exporter_script1
    files:
    - script_exporter/script1.sh