apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
#  - ingress/middleware.yaml

  - deployment.yaml
  - service/service.yaml
  - exporters/pgbouncer-exporter/deployment.yaml
  - exporters/pgbouncer-exporter/service.yaml
  - exporters/postgres-exporter/deployment.yaml
  - exporters/postgres-exporter/service.yaml

configMapGenerator:
  - name: script-exporter-config
    files:
    - script_exporter/config.yaml
  - name: script-exporter-script1
    files:
    - script_exporter/script1.sh


generatorOptions:
  disableNameSuffixHash: true