apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana/kustomization.yaml
  - prometheus/kustomization.yaml


  - ingress/middleware.yaml
  - ingress/yopass-ingress.yaml

  - deployment.yaml
  - service/service.yaml