apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
#  - ingress/middleware.yaml

  - deployment.yaml
  - service/service.yaml
  - zabbix-server/deployment.yaml
  - zabbix-server/service/service.yaml
  - zabbix-web/deployment.yaml
  - zabbix-web/service/service.yaml
  - zabbix-web/service/ingressroute.yaml

configMapGenerator:
  - name: script-exporter-config
    files:
    - script_exporter/config.yaml
  - name: script-exporter-script1
    files:
    - script_exporter/script1.sh


generatorOptions:
  disableNameSuffixHash: true