apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:5.0.34-alpine
        ports:
        - name: zabbix-trapper
          containerPort: 10051
        envFrom:
        - configMapRef:
            name: vcenter-exporter-env
        resources:    
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 2
            memory: 500Mi    
        env:
        - name: PHP_TZ
          value: "Europe/Stockholm"
#            - name: MYSQL_USER
#              valueFrom:
#               secretKeyRef:
#                name: mysql-secret
#                key: mysql-zbx-user
#            - name: MYSQL_PASSWORD
#              valueFrom:
#               secretKeyRef:
#                name: mysql-secret
#                key: mysql-zbx-pass
#            - name: MYSQL_ROOT_PASSWORD
#              valueFrom:
#               secretKeyRef:
#                name: mysql-secret
#                key: mysql-root-pass
        - name: POSTGRES_USE_IMPLICIT_SEARCH_PATH
          value: "true"
        - name: DB_SERVER_HOST
          value: "192.168.103.10"
        - name: DB_SERVER_PORT
          value: "5000"
        - name: POSTGRES_USER
          value: zabbix
        - name: POSTGRES_PASSWORD
          value: zabbix
        - name: ZBX_CACHESIZE
          value: "1024M"
        - name: ZBX_TRENDCACHESIZE
          value: "1024M"
        - name: ZBX_HISTORYCACHESIZE
          value: "2048M"
        - name: ZBX_HISTORYINDEXCACHESIZE
          value: "1024M"
        - name: ZBX_STARTTRAPPERS
          value: "5"
        - name: ZBX_STARTPREPROCESSORS
          value: "10"
        - name: ZBX_STARTDBSYNCERS
          value: "10"
        - name: ZBX_JAVAGATEWAY_ENABLE
          value: "true"
        - name: ZBX_STARTJAVAPOLLERS
          value: "5"
        - name: ZBX_ENABLE_SNMP_TRAPS
          value: "true"
        - name: ZBX_STARTPROXYPOLLERS
          value: "5"
        - name: ZBX_PROXYCONFIGFREQUENCY
          value: "60"              
      restartPolicy: Always
  revisionHistoryLimit: 1