apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-01
                - worker-02
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:7.0.16-alpine
        ports:
        - name: zabbix-trapper
          containerPort: 10051
        resources:    
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 350Mi    
        envFrom:
        - secretRef:
            name: zabbixdb
        env:
        - name: PHP_TZ
          value: "Europe/Stockholm"
        - name: POSTGRES_USE_IMPLICIT_SEARCH_PATH
          value: "true"
        - name: ZBX_CACHESIZE
          value: "64M" #default 8M
        - name: ZBX_TRENDCACHESIZE
          value: "4M" #Default 4M
        - name: ZBX_HISTORYCACHESIZE
          value: "16M" # Default 16M
        - name: ZBX_HISTORYINDEXCACHESIZE
          value: "4M" # Default 4m
        - name: ZBX_STARTDBSYNCERS
          value: "4" #Default 4
        - name: ZBX_PROXYCONFIGFREQUENCY
          value: "120"              
        - name: ZBX_DEBUGLEVEL
          value: "3"
        - name: ZBX_LOGSLOWQUERIES
          value: "3000"
      restartPolicy: Always
  revisionHistoryLimit: 1
