apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:6.0.18-alpine
        ports:
        - name: zabbix-trapper
          containerPort: 10051
        resources:    
          requests:
            cpu: 300m
            memory: 400Mi
          limits:
            cpu: 4
            memory: 1000Mi    
        envFrom:
        - secretRef:
            name: zabbixdb
        env:
        - name: PHP_TZ
          value: "Europe/Stockholm"
        - name: POSTGRES_USE_IMPLICIT_SEARCH_PATH
          value: "true"
        - name: ZBX_CACHESIZE
          value: "128M"
#        - name: ZBX_TRENDCACHESIZE
#          value: "1024M"
#        - name: ZBX_HISTORYCACHESIZE
#          value: "2048M"
#        - name: ZBX_HISTORYINDEXCACHESIZE
#          value: "1024M"
#        - name: ZBX_STARTTRAPPERS
#          value: "5"
#        - name: ZBX_STARTPREPROCESSORS
#          value: "10"
        - name: ZBX_STARTDBSYNCERS
          value: "4" #Default 4
#        - name: ZBX_JAVAGATEWAY_ENABLE
#          value: "true"
#        - name: ZBX_STARTJAVAPOLLERS
#          value: "5"
        - name: ZBX_ENABLE_SNMP_TRAPS
          value: "true"
#        - name: ZBX_STARTPROXYPOLLERS
#          value: "10"
        - name: ZBX_PROXYCONFIGFREQUENCY
          value: "600"              
#        - name: ZBX_STARTHTTPPOLLERS
#          value: "5"
#        - name: ZBX_STARTESCALATORS
#          value: "5"
      restartPolicy: Always
  revisionHistoryLimit: 1