apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: traefik
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  annotations:
    metallb.universe.tf/address-pool: default

spec:
  type: LoadBalancer
  #  loadBalancerIP: 192.168.100.30
  selector:
    app: traefik


  ports:
    - name: http
      protocol: TCP
      port: 80

    - name: https
      protocol: TCP
      port: 443

    - name: admin
      protocol: TCP
      port: 8080
