apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zabbix-server
resources:
 - ingress/middleware.yaml
 - zabbix-server/deployment.yaml
 - zabbix-server/service/service.yaml
 - zabbix-web/deployment.yaml
 - zabbix-web/service/service.yaml
 - zabbix-web/service/ingressroute.yaml
 - zabbix-web/service/certificate.yaml
 - proxyservice.yaml
generatorOptions:
  disableNameSuffixHash: true