apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy-en
  namespace: zabbix-server
  annotations:
    metallb.universe.tf/address-pool: pool07-zabbixproxy-bgp
spec:
  type: ExternalName
  externalName: zabbix-proxy.zabbix-agent
  ports:
    - name: zabbix
      port: 10050
      protocol: TCP
  externalIPs:
    - 192.168.201.23