apiVersion: apps/v1
kind: Deployment
metadata:
  name: yopass
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yopass
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yopass
    spec:
      containers:
      - name: yopass
        image: jhaals/yopass:11.4.6
        args:
          - "--database=redis"
          - "--redis=redis://yopass-redis:6379/0"
          - "--port=8080"
        ports:
        - name: http
          containerPort: 8080
        resources: 
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
  revisionHistoryLimit: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yopass-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yopass-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yopass-redis
    spec:
      containers:
      - name: yopass-redis
        image: redis:7.0.5-alpine
        args:
        - "--save 60 1"
        - "--loglevel warning"
        - "--maxmemory 48mb"
        - "--maxmemory-policy noeviction"
        ports:
        - name: redis
          containerPort: 6379
        resources: 
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts: 
          - name: redis-data
            mountPath: /data
      restartPolicy: Always
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: yopass-redis-pvc
  revisionHistoryLimit: 2