apiVersion: apps/v1
kind: Deployment
metadata:
  name: yopass
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yopass
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yopass
    spec:
      containers:
        - name: yopass
          image: jhaals/yopass:11.4.3
          args:
            - "--memcached=localhost:11211"
            - "--port=8080"
          ports:
            - name: http
              containerPort: 8080
        - name: yopass-memcached
          image: memcached:1.6.15
          args:
            - "-m 64"
          ports:
            - name: memcached
              containerPort: 11211
      restartPolicy: Always
