apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - redis/redis-pvc.yaml
  - redis/service.yaml
  - yopass/service.yaml
  - yopass/middleware.yaml
  - yopass/yopass-ingress.yaml
  - yopass/deployment.yaml
  - redis/deployment.yaml
  - yopass/certificate.yaml