apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/function: db
    app.kubernetes.io/kind: MySQL
    app.kubernetes.io/service: yopass-redis
  name: yopass-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi