metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
spec:
  externalIPs:
  - 192.168.100.20
  selector:
    app.kubernetes.io/name: argocd-server
status:
  loadBalancer: {}
