apiVersion: v1
kind: Service
metadata:
  labels:
    application: kube-ops-view
    component: frontend
  name: kube-ops-view
spec:
  selector:
    application: kube-ops-view
    component: frontend
  type: ClusterIP
  externalIPs:
  - 192.168.100.21
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
