apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: cert-postfixadmin-k8s-lenin-nu
spec:
  dnsNames:
    - "postfixadmin.k8s.lenin.nu"
  secretName: postfixadmin-k8s-lenin-nu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always