apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfixadmin
  labels:
    app.kubernetes.io/name: postfixadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postfixadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postfixadmin
    spec:
      containers:
        - name: postfixadmin
          image: postfixadmin:3.3.13-apache
          ports:
          - name: http
            containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: "1"
              memory: 512M
          env:
          - name: POSTFIXADMIN_DB_TYPE
            value: "pgsql"
          - name: POSTFIXADMIN_DB_HOST
            value: "192.168.103.10"
          - name: POSTFIXADMIN_DB_USER
            value: "postfixadmin"
          - name: POSTFIXADMIN_DB_PORT
            value: "5000"
          - name: POSTFIXADMIN_DB_PASSWORD
            value: "postfixadmin"
          - name: POSTFIXADMIN_DB_NAME
            value: "postfixadmin"
          - name: POSTFIXADMIN_SETUP_PASSWORD
            value: "$2y$10$RVIu7OmGtWHxa0W3g0I5eOGVbAHc3e7HB40WTaZKSCAb3Ryf78ow6"
  revisionHistoryLimit: 1
