apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: cert-harbor-k8s-lenin-nu
spec:
  dnsNames:
    - "harbor.k8s.lenin.nu"
  secretName: secret-harbor-k8s-lenin-nu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  revisionHistoryLimit: 1