apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-https
spec:
  entryPoints:
    - websecure
  tls:
    secretName: secret-harbor-k8s-lenin-nu
  routes:
  - match: Host(`harbor.k8s.lenin.nu`)
    kind: Rule
    middlewares:
    - name: ipwhitelist-privnets
    services:
    - name: harbor-portal
      port: 80
  - match: Host(`harbor.k8s.lenin.nu`) && PathPrefix(`/api/`)
    kind: Rule
    middlewares:
    - name: ipwhitelist-privnets
    services:
    - name: harbor-core
      port: 80
  - match: Host(`harbor.k8s.lenin.nu`) && PathPrefix(`/service/`)
    kind: Rule
    middlewares:
    - name: ipwhitelist-privnets
    services:
    - name: harbor-core
      port: 80
  - match: Host(`harbor.k8s.lenin.nu`) && PathPrefix(`/v2/`)
    kind: Rule
    middlewares:
    - name: ipwhitelist-privnets
    services:
    - name: harbor-core
      port: 80
  - match: Host(`harbor.k8s.lenin.nu`) && PathPrefix(`/chartrepo/`)
    kind: Rule
    middlewares:
    - name: ipwhitelist-privnets
    services:
    - name: harbor-core
      port: 80
  - match: Host(`harbor.k8s.lenin.nu`) && PathPrefix(`/c/`)
    kind: Rule
    middlewares:
    - name: ipwhitelist-privnets
    services:
    - name: harbor-core
      port: 80
#---
#apiVersion: traefik.io/v1alpha1
#kind: IngressRoute
#metadata:
#  name: harbor-notary-https
#spec:
#  entryPoints:
#    - websecure
#  tls:
#    secretName: secret-harbor-notary-k8s-lenin-nu
#  routes:
#  - match: Host(`harbor-notary.k8s.lenin.nu`)
#    kind: Rule
#    middlewares:
#    - name: ipwhitelist-privnets
#    services:
#    - name: harbor-notary-server
#      port: 4443