apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.8/manifests/install.yaml
  - service/argocd-rescue.yaml
  - ingress/argocd-ingress.yaml
  - ingress/middleware.yaml
patchesStrategicMerge:
  - patch/argocd-cmd-params-cm-patch.yml