apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.3/manifests/install.yaml
  - service/argocd-rescue.yaml
  - service/argocd-rescue2.yaml
  - ingress/argocd-ingress.yaml
  - ingress/middleware.yaml
patchesStrategicMerge:
  - patch/argocd-cm.yaml
  - patch/argocd-clusterrole.yaml