apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - middlewares/middleware.yaml
  - pravda/deployment.yaml
  - pravda/services.yaml
  - pravda/ingressroute.yaml

configMapGenerator:
  - name: html-pravda-index
    files:
    - pravda/index.html