
namespace: metallb-system

resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/manifests/namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/manifests/metallb.yaml

  - config/configmap.yaml

generatorOptions:
  disableNameSuffixHash: true