
namespace: metallb-system

resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml

configMapGenerator:
  - name:config
    files:
    - config/metallb-config.yaml

generatorOptions:
  - disableNameSuffixHash: true
