
namespace: metallb-system

resources:
  - github.com/metallb/metallb/main/manifests/namespace.yaml?ref=v0.12.1
  - github.com/metallb/metallb/main/manifests/metallb.yaml?ref=v0.12.1
  - config/metallb-config.yaml
