apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  labels:
    app.kubernetes.io/name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - zabbix-web
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:6.0.23-alpine
          resources:
            limits:
              cpu: 1
              memory: 512M
            requests:
              cpu: 100m
              memory: 128M
          ports:
          - containerPort: 8080
          envFrom:
          - secretRef:
              name: zabbixdb
          env:
          - name: ZBX_SERVER_HOST
            value: "zabbix-server-svc"
          - name: ZBX_SERVER_PORT
            value: "10051"
          - name: POSTGRES_USE_IMPLICIT_SEARCH_PATH
            value: "true"
  revisionHistoryLimit: 1
