apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts3bot
  annotations:
    another-autoscaler/start-time: "00-20 20 * * 4"
    another-autoscaler/start-replicas: "1"
    another-autoscaler/stop-time: "50-59 23 * * 4"
    another-autoscaler/stop-replicas: "0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ts3bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ts3bot
    spec:
      containers:
      - name: ts3bot
        image:  cmdrlenin/ts3audiobot3.1:0.12.0
        volumeMounts:
        - name: ts3-bot-config
          mountPath: /app/data/rights.toml
          subPath: rights.toml
        - name: ts3-bot-config
          mountPath: /app/data/ts3audiobot.toml
          subPath: ts3audiobot.toml
        - name: ts3-bot-config
          mountPath: /app/data/bots/HuttonChatDisabled/bot.toml
          subPath: chatDisabled.toml
        - name: ts3-bot-config
          mountPath: /app/data/bots/HuttonChatEnabled/bot.toml
          subPath: chatEnabled.toml
        resources: 
          limits:
            cpu: 400m
            memory: 256M
          requests:
            cpu: 200m
            memory: 128M
      restartPolicy: Always
      volumes:
      - name: ts3-bot-config
        configMap:
          name: ts3-bot-config
  revisionHistoryLimit: 1