apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mail
resources:

  - postfixadmin/deployment.yaml
  - postfixadmin/service.yaml
  - postfixadmin/ingressroute.yaml
  - postfixadmin/middleware.yaml

generatorOptions:
  disableNameSuffixHash: true