apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: cert-gunvor-lindblad.net
spec:
  dnsNames:
    - "gunvor.lindblad.net"
  secretName: secret-gunvor-lindblad.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  revisionHistoryLimit: 1