apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  labels:
    app.kubernetes.io/app: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: zabbix-web
  template:
    metadata:
      labels:
        app.kubernetes.io/app: zabbix-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - zabbix-web
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:6.0.8-alpine
          ports:
          - name: http
            containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: "1"
              memory: 512M
          env:
          - name: ZBX_SERVER_HOST
            value: "zabbix-server"
#          - name: ZBX_SERVER_PORT
#            value: 10051
          - name: DB_SERVER_HOST
            value: "192.168.103.10"
          - name: DB_SERVER_PORT
            value: "5000"
          - name: POSTGRES_USER
            value: "zabbix"
          - name: POSTGRES_PASSWORD
  revisionHistoryLimit: 1
