apiVersion: apps/v1
kind: Deployment
metadata:
  name: yopass-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yopass-redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yopass-redis
    spec:
      containers:
      - name: yopass-redis
        image: redis:7.4.0-alpine
        args:
        - "--save 60 1"
        - "--loglevel warning"
        - "--maxmemory 48mb"
        - "--maxmemory-policy noeviction"
        ports:
        - name: redis
          containerPort: 6379
        resources: 
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts: 
          - name: redis-data
            mountPath: /data/
      restartPolicy: Always
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: yopass-redis-pvc
  revisionHistoryLimit: 1